joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

left_wheel_effort_controller:
  type: effort_controllers/JointEffortController
  joint: left_wheel_joint
  pid: {p: 20.0, i: 0.01, d: 0.1}

right_wheel_effort_controller:
  type: effort_controllers/JointEffortController
  joint: right_wheel_joint
  pid: {p: 20.0, i: 0.01, d: 0.1}
